"""Add views and clicks to Post

Revision ID: 902f1373d2af
Revises: deb2f68722a6
Create Date: 2025-06-11 02:50:47.978743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '902f1373d2af'
down_revision = 'deb2f68722a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('views', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('views')

    # ### end Alembic commands ###
